name: "Python Testing with casatools"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.rst"

jobs:
  call-testing-with-casatools:
    uses: nrao/gh-actions-templates-public/.github/workflows/python-testing-casatools-template.yml@main
    with:
      cov_project: "xradio"
      test-path: "tests/"
      pytest_ignore: "tests/unit/measurement_set"
    secrets: inherit
